# Pytorch 

Core Use Case -
 - replace the numpy to use GPU's for fast compilation
 - automatic differntiation which can help in calculation gradients => we can implement ANN's 



In [1]:
import torch
import numpy as np

# Tensors
* A kind of Data-Structures => Multi Dimensional array or matrices
with tensors you encode all your parameters.

In [2]:
data = [[9, 10], [4, 5], [12, 13]]

In [3]:
# Creating a tensor
tensor_data = torch.tensor(data)
tensor_data

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])

In [4]:
type(tensor_data)

torch.Tensor

In [5]:
tensor_data[0][0]

tensor(9)

In [6]:
data_np = np.array([[9, 10], [4, 5], [12, 13]])
# Creating a tensor
tensor_data = torch.tensor(data_np)
print(tensor_data)
print(type(tensor_data))
print(tensor_data[0][0])

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])
<class 'torch.Tensor'>
tensor(9)


In [7]:
# Ones like
ones = torch.ones_like(tensor_data)
ones

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [8]:
# Random like
random = torch.rand_like(tensor_data)
random

RuntimeError: ignored

In [ ]:
# Ransom like
random = torch.rand_like(tensor_data, dtype=torch.float)
random

In [9]:
# We can use this for weights initilization
shape = (4, 3, 2)
# Range is between 0 to 1
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[[0.8413, 0.2106],
         [0.1503, 0.2197],
         [0.7882, 0.0890]],

        [[0.8294, 0.8357],
         [0.4170, 0.2673],
         [0.0637, 0.7120]],

        [[0.4700, 0.0930],
         [0.0627, 0.0737],
         [0.3217, 0.0788]],

        [[0.2957, 0.1053],
         [0.5266, 0.1726],
         [0.7890, 0.6464]]])

In [10]:
rand_tensor.shape

torch.Size([4, 3, 2])

In [11]:
# We can use this for bias initilization
one = torch.ones(shape)
one

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [12]:
zero = torch.zeros(shape)
zero

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [13]:
one = torch.ones(shape)
one * 5

tensor([[[5., 5.],
         [5., 5.],
         [5., 5.]],

        [[5., 5.],
         [5., 5.],
         [5., 5.]],

        [[5., 5.],
         [5., 5.],
         [5., 5.]],

        [[5., 5.],
         [5., 5.],
         [5., 5.]]])

In [14]:
rand_tensor.dtype

torch.float32

In [15]:
rand_tensor.device

device(type='cpu')

In [16]:
torch.cuda.is_available()

True

In [20]:
# Connect the gpu then run this
current_device = torch.cuda.current_device()

In [22]:
torch.cuda.get_device_name(current_device)

'Tesla T4'

In [26]:
!nvidia-smi

Tue Feb 28 07:40:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [27]:
if torch.cuda.is_available():
    tensor = rand_tensor.to("cuda")
    print(tensor.device)

cuda:0


In [ ]:
# Concat Operations
# ASIC :- Application Specific Interagrated Circut

In [28]:
ones = torch.ones(2, 2)

In [30]:
torch.cat([ones, ones])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [31]:
torch.cat([ones, ones], dim=1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Arithmetic Operations

In [32]:
# @ is for matrix multiplication
y = ones @ ones.T
y

tensor([[2., 2.],
        [2., 2.]])

In [33]:
y = ones.matmul(ones.T)
y

tensor([[2., 2.],
        [2., 2.]])

In [35]:
# For dot operation
y = ones * ones
y

tensor([[1., 1.],
        [1., 1.]])

In [71]:
y = ones.mul(ones)
y

tensor([[1., 1.],
        [1., 1.]])

In [39]:
five = ones + 5

In [40]:
# inplace operation
five.add_(5)

tensor([[11., 11.],
        [11., 11.]])

In [42]:
five

tensor([[11., 11.],
        [11., 11.]])

In [43]:
type(ones)

torch.Tensor

In [45]:
ones_np = ones.numpy()
type(ones_np)

numpy.ndarray

In [50]:
ones_tensor = torch.from_numpy(data_np)
type(ones_tensor)

torch.Tensor

# Analysis on Fashion Mnest Using Torch 

In [51]:
# Importing the libraries
import torch
from torch import nn
# For all computer vision task we use torch vision
import torchvision
import matplotlib.pyplot as plt

In [52]:
# Name of the root directory
ROOT = "FashionMnist"

In [54]:
# Downloading the train data
train_data = torchvision.datasets.FashionMNIST(
    root = ROOT,
    train = True,
    download = True,
    transform = torchvision.transforms.ToTensor() #Converting np array to tensor
)

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting FashionMnist/FashionMNIST/raw/train-images-idx3-ubyte.gz to FashionMnist/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting FashionMnist/FashionMNIST/raw/train-labels-idx1-ubyte.gz to FashionMnist/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting FashionMnist/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to FashionMnist/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting FashionMnist/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to FashionMnist/FashionMNIST/raw



In [55]:
# Downloading the test data
test_data = torchvision.datasets.FashionMNIST(
    root = ROOT,
    train = False,
    download = True,
    transform = torchvision.transforms.ToTensor()
)

In [57]:
# Defining the batch size
BATCH_SIZE = 64
# Data loader will load the dataset one by one 
train_data_loader = torch.utils.data.DataLoader(train_data, batch_size=BATCH_SIZE)
test_data_loader = torch.utils.data.DataLoader(test_data, batch_size=BATCH_SIZE)

In [64]:
# Checking the shape of the dataset
for X, y in test_data_loader:
    print(X.shape, X.dtype)
    print(y.shape, y.dtype, torch.unique(y))
    break

torch.Size([64, 1, 28, 28]) torch.float32
torch.Size([64]) torch.int64 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [65]:
# Checking if Cuda is available
device = "cuda" if torch.cuda.is_available() else "CPU"

In [66]:
device

'cuda'

# Creating a Neural Network

In [80]:
# Defining a newralnetwork
class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()

        self.flatten = nn.Flatten()
        
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512), #512 is number of neurons
            nn.ReLU(),
            nn.Linear(512, 512), #512 is number of neurons
            nn.ReLU(),
            nn.Linear(512, 10), #512 is number of neurons
            nn.ReLU()
        )
    
    # Forward propgation
    def forward(self, X):
        X = self.flatten(X)
        #logits will the values betwwn -inf to +inf
        logits = self.linear_relu_stack(X)
        return logits

In [81]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


In [82]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [83]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)

    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device) #for GPU

        # Calculate error and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Back propagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"Trainig loss: {loss} [{current}/{size}]")

In [88]:
def test(dataloader, model):
    size = len(dataloader.dataset)
    model.eval()

    test_loss, correct = 0, 0
    
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss  = test_loss + loss_fn(pred, y).item()
            correct = correct + (pred.argmax(1) == y).type(torch.float).sum().item()
    
    test_loss = test_loss / size
    correct = correct / size
    print(f"\"Test Error\" : {100 * correct}, average loss: {test_loss}")

In [89]:
EPOCHS = 3
for epoch in range(EPOCHS):
    print(f"EPOCH: {epoch +1 }\n-------------")
    train(train_data_loader, model, loss_fn, optimizer)
    test(test_data_loader, model)
print("Done")

EPOCH: 1
-------------
Trainig loss: 1.9886010885238647 [0/60000]
Trainig loss: 1.9702329635620117 [6400/60000]
Trainig loss: 1.8529287576675415 [12800/60000]
Trainig loss: 1.9555460214614868 [19200/60000]
Trainig loss: 1.8299469947814941 [25600/60000]
Trainig loss: 1.7720507383346558 [32000/60000]
Trainig loss: 1.8812751770019531 [38400/60000]
Trainig loss: 1.7162449359893799 [44800/60000]
Trainig loss: 1.7922412157058716 [51200/60000]
Trainig loss: 1.800118327140808 [57600/60000]
"Test Error" : 55.300000000000004, average loss: 0.026574853134155273
EPOCH: 2
-------------
Trainig loss: 1.7186464071273804 [0/60000]
Trainig loss: 1.7010401487350464 [6400/60000]
Trainig loss: 1.5228831768035889 [12800/60000]
Trainig loss: 1.7095813751220703 [19200/60000]
Trainig loss: 1.5405919551849365 [25600/60000]
Trainig loss: 1.5005038976669312 [32000/60000]
Trainig loss: 1.674136996269226 [38400/60000]
Trainig loss: 1.4630151987075806 [44800/60000]
Trainig loss: 1.580603837966919 [51200/60000]
Trai

In [90]:
# Saving the model
torch.save(model, "model.pth")

In [92]:
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot"
]

In [98]:
model.eval()
X, y = test_data[0][0], test_data[0][1]

with torch.no_grad():
    X = X.to(device)
    # model.to("cpu")
    # y = y.to(device)
    pred = model(X)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f"Predicted {predicted}, Actual {actual}")

Predicted Ankle boot, Actual Ankle boot
